### ISSUE TITLE
[feature] .recover as a driver function

### ISSUE THREAD

**Issue by blackheart01** [DBD-SQLite/DBD-SQLite#102]
Hopefully this is the right place for a feature request.

SQLite has added the .recover dot command to the command line sqlite tool. You can find the code for it in shell.c that comes with the sqlite3 source code as the recoverDatabaseCmd function.

The .recover command is the new preferred method of recovering a malformed database, and the documentation can be seen here https://www.sqlite.org/cli.html#recover_data_from_a_corrupted_database.

It would be very useful to have access to this function as a DBD::SQLite driver function, similar to DBD::SQLite::compile_options().

I don't currently understand how perl modules include c code and work with xs. I'm trying to get a grasp on it, but perhaps someone more skilled in this area could tackle it for the community or even just provide some guidance on what it would take to accomplish this.

Thanks for any feedback!

**Comment by hoehrmann** [comment]
It might make sense to request on the SQLite forums, then, that this functionality be exposed through the SQLite API with suitable C-functions. The shell.c CLI is not meant to be linked into database drivers like DBD::SQLite, and using the code by copy&paste from some version of shell.c risks becoming out of sync with the original, with possibly harmful effects in future versions of SQLite. I would expect various SQLite GUIs for instance would also like to expose the functionality without going through shell.c code.

**Comment by blackheart01** [comment]
@hoehrmann that makes perfect sense. I spent a day digging into the code and felt the same way. I'll make a post on the sqlite forums.

I have to spend a little more time looking into the code, but it does look like the c code just builds up sql queries to run. No magic under the hood. So I may rewrite the logic in perl, or just make a new module that simply links that code, rather than trying to include it in DBD::SQLite. It looks like perl provides all the tools needed to get the job done quickly, just gotta spend some time learning how its done.

Either way, I'll see if there's any interest in the sqlite forums to get the code migrated into the sqlite api.
