### ISSUE TITLE
51_table_column_metadata.t fails for 1.72

### ISSUE THREAD

**Issue by perlpunk** [DBD-SQLite/DBD-SQLite#104]
We currently see this failure on openSUSE Leap 15.4, perl 5.36.0,  libsqlite3-0-3.39.4-1.1, sqlite3-devel-3.39.4-1.1:
```
[   27s] 
[   27s] #   Failed test 'data type is correct'
[   27s] #   at t/51_table_column_metadata.t line 22.
[   27s] #          got: 'integer'
[   27s] #     expected: 'INTEGER'
[   27s] 
[   27s] #   Failed test 'data type is correct'
[   27s] #   at t/51_table_column_metadata.t line 22.
[   27s] #          got: 'integer'
[   27s] #     expected: 'INTEGER'
[   27s] # Looks like you failed 2 tests of 32.
[   27s] t/51_table_column_metadata.t .......................... 
[   27s] Dubious, test returned 2 (wstat 512, 0x200)
[   27s] Failed 2/32 subtests 
```
The full log can be found here: https://build.opensuse.org/package/live_build_log/devel:languages:perl:autoupdate/perl-DBD-SQLite/standard/x86_64

**Comment by charsbar** [comment]
@perlpunk , thanks for the report. Hmm, could you tell if you apply a patch for dbdimp.c, esp around https://github.com/DBD-SQLite/DBD-SQLite/blob/master/dbdimp.c#L1982 and https://github.com/DBD-SQLite/DBD-SQLite/blob/master/dbdimp.c#L1931-L1944? If they don't work, I can `lc` https://github.com/DBD-SQLite/DBD-SQLite/blob/master/t/51_table_column_metadata.t#L22 but I'd like to know if you have done something to DBD::SQLite first.

**Comment by perlpunk** [comment]
I can try out a patch. What should I change?

**Comment by charsbar** [comment]
@perlpunk If you, or openSUSE people, don't apply any in-house patch for openSUSE, then I'm not sure what's happening for now, but if the code linked above doesn't work, then I'd just apply something like the following:
```
diff --git a/t/51_table_column_metadata.t b/t/51_table_column_metadata.t
index f6a6d70..7c63b59 100644
--- a/t/51_table_column_metadata.t
+++ b/t/51_table_column_metadata.t
@@ -19,7 +19,7 @@ for my $call_func (@CALL_FUNCS) {
                my $data = $dbh->$call_func(undef, 'foo', 'id', 'table_column_metadata');
                ok $data && ref $data eq ref {}, "got a metadata";
                ok $data->{auto_increment}, "id is auto incremental";
-               is $data->{data_type} => 'integer', "data type is correct";
+               is lc($data->{data_type}) => 'integer', "data type is correct";
                ok $data->{primary}, "id is a primary key";
                ok !$data->{not_null}, "id is not null";
        }
```
Or, if you find anything wrong in https://github.com/DBD-SQLite/DBD-SQLite/blob/master/dbdimp.c#L1931-L1944, I'd be happy to apply a patch from you or openSUSE people.

**Comment by perlpunk** [comment]
No, we're currently not applying any patch.
https://build.opensuse.org/package/show/devel:languages:perl/perl-DBD-SQLite
I'll add your suggested patch, thanks.

**Comment by perlpunk** [comment]
Sorry, I was just blind.
We are using a patch called `perl-DBD-SQLite-use-external-sqlite3.patch`, which contained the reverse of your suggested patch :)
Not sure why I didn't see it.
All green now :)
