### ISSUE TITLE
Garbage in sqlite_unprepared_statements with sqlite_unicode and prepare_cached

### ISSUE THREAD

**Issue by Grinnz** [DBD-SQLite/DBD-SQLite#11]
I have run into an issue when trying to implement Mojo::SQLite::Migrations (I worked around it by using ->do for the migrations instead for now). The attached testcase demonstrates the issue; the second time the "select exists..." query is run, it leaves some garbage in sqlite_unprepared_statements which is usually not a valid query. It seems like an XS issue. If the query is prepared with prepare() instead of prepare_cached(), or sqlite_unicode is not set, the issue does not occur.

https://gist.github.com/Grinnz/9d6284fe36ec7d40249c

Output:
````
ok 1 - Table does not exist
DBD::SQLite::db prepare_cached failed: near "Íø": syntax error at dbd-sqlite-test.pl line 11.
````
(syntax error is random)

**Comment by charsbar** [comment]
Hi, this is because unprepared_statements is just a pointer to the statement prepared previously. The simplest fix should be the following, but I'm not 100% sure yet if it is really worth the cost to save and free this rarely-used (and rarely-useful) item each time prepare is called. (It might be better to document not to use this attribute with prepare_cached). Try also sqlite_allow_multiple_statements attribute, which might work better for you.

```
index a4e426b..a577653 100644
--- a/dbdimp.c
+++ b/dbdimp.c
@@ -896,9 +896,10 @@ sqlite_st_prepare_sv(SV *sth, imp_sth_t *imp_sth, SV *sv_statement, SV *attribs)
         return FALSE; /* -> undef in lib/DBD/SQLite.pm */
     }
     if (&extra) {
-        imp_sth->unprepared_statements = extra;
+        imp_sth->unprepared_statements = savepv(extra);
     }
     else {
+        Safefree(imp_sth->unprepared_statements);
         imp_sth->unprepared_statements = NULL;
     }
     /* Add the statement to the front of the list to keep track of
@@ -1295,6 +1296,7 @@ sqlite_st_destroy(SV *sth, imp_sth_t *imp_sth)
             imp_sth->stmt = NULL;
         }
     }
+    Safefree(imp_sth->unprepared_statements);
     SvREFCNT_dec((SV*)imp_sth->params);
     SvREFCNT_dec((SV*)imp_sth->col_types);
     DBIc_IMPSET_off(imp_sth);
```

**Comment by Grinnz** [comment]
I am using sqlite_allow_multiple_statements currently with do(), but that does not affect manual prepare/execute, it would be nice to be able to cache these statements as well but still allow multiple statements. I am not sure about the XS part but would it be possible to have allow_multiple_statements also affect making sure unprepared_statements is usable with prepare_cached? Thanks for your help.

**Comment by charsbar** [comment]
Done, and will add a note to doc later. Thanks.
