### ISSUE TITLE
Recommended way to report a (low impact) security issue

### ISSUE THREAD

**Issue by iosifache** [DBD-SQLite/DBD-SQLite#110]
Hi DBD-SQLite team,

Could you please point me in the direction of where I should submit an issue that may have (limited) security implications? Unfortunately, there is no security policy or suggestions in `README.md`, so I'm stuck.

**Comment by charsbar** [comment]
Could you please send me (ishigaki@cpan.org) an email?

**Comment by iosifache** [comment]
Sure. Thanks, @charsbar 🙏🏻!

**Comment by setharnold** [comment]
Please consider adding a `SECURITY.md` or similar so researchers will know your preferences. Thanks :)
