### ISSUE TITLE
SCO 5.0.7v make fails, fchmod missing in sqlite3.c

### ISSUE THREAD

**Issue by dnadle** [DBD-SQLite/DBD-SQLite#13]
I had to add #include sys/stat.h to the top of sqlite3.c to get it to build on SCO 5.0.7v.

**Comment by charsbar** [comment]
@dnadle, it looks like that the upstream SQLite library doesn't recognize your platform correctly or something. Please fetch the source of SQLite itself from http://sqlite.org/download.html , and build and test it to see if it actually works for you. If it doesn't, report the issue to the upstream mailing list (see http://sqlite.org/support.html ) If it does, then let me know more of your environment (by pasting the result of perl -V etc).
