### ISSUE TITLE
[PATCH] Fix spelling error in manpage

### ISSUE THREAD

**Issue by carnil** [DBD-SQLite/DBD-SQLite#15]
Hi,

In Debian we are currently applying the following patch to
DBD-SQLite.
We thought you might be interested in it too.

    Description: Fix spelling error in manpage
    Origin: vendor
    Author: Salvatore Bonaccorso <carnil@debian.org>
    Last-Update: 2016-02-14
    

The patch is tracked in our Git repository at
https://anonscm.debian.org/cgit/pkg-perl/packages/libdbd-sqlite3-perl.git/plain/debian/patches/spelling-error-in-manpage.patch

Thanks for considering,
  Salvatore Bonaccorso,
  Debian Perl Group

**Comment by charsbar** [comment]
Thanks!
