### ISSUE TITLE
Please add a complete whatis entry for lib/DBD/SQLite/Constants.pm

### ISSUE THREAD

**Issue by carnil** [DBD-SQLite/DBD-SQLite#16]
Hi

The (generated) lib/DBD/SQLite/Constants.pm POD does not contain a complete whatis entry. The NAME which should list the name, but a brief description (separted by a \-) is missing.

This triggers a warning from the QA tools in Debian (https://lintian.debian.org/tags/manpage-has-bad-whatis-entry.html)

Could you add as well a brief description of the module to the autogenerated POD?

Regards and thanks for your work!
Salvatore

**Comment by charsbar** [comment]
Thanks for the heads-up.
