### ISSUE TITLE
Shared cache mode

### ISSUE THREAD

**Issue by zdm** [DBD-SQLite/DBD-SQLite#19]
Hi.
Is it possible to add possibility to enable shared cache mode?
API call: int sqlite3_enable_shared_cache(int);

https://www.sqlite.org/c3ref/enable_shared_cache.html

**Comment by charsbar** [comment]
Hi. I suppose the following sqlite_open_flags should work with recent DBD::SQLite (sorry I don't remember since when). Let me know if it's not enough for you.

```
use DBI;
use DBD::SQLite::Constants qw/:file_open/;
my $dbh = DBI->connect("dbi:SQLite:$dbfile", undef, undef, {
  sqlite_open_flags => SQLITE_OPEN_SHAREDCACHE,
});
```

**Comment by zdm** [comment]
This works, thanks.
