### ISSUE TITLE
incorrect database name when trying to open

### ISSUE THREAD

**Issue by troogyt** [DBD-SQLite/DBD-SQLite#33]
I think there is a bug whereby the 'real' db name is not assigned immediately before trying to open the db.
I suspect the issue is on line 96 when the key/value pairs are separated using 'split' on matching the '=':

Lines 93-106:
```
    my $real = $dbname;
    if ( $dbname =~ /=/ ) {
        foreach my $attrib ( split(/;/, $dbname) ) {
            my ($key, $value) = split(/=/, $attrib, 2);
            if ( $key =~ /^(?:db(?:name)?|database)$/ ) {
                $real = $value;
            } elsif ( $key eq 'uri' ) {
                $real = $value;
                $attr->{sqlite_open_flags} |= DBD::SQLite::OPEN_URI();
            } else {
                $attr->{$key} = $value;
            }
        }
    }

```
I ran Process Monitor and found that perl was trying to open the DB:
"C:\Users\username\eclipse-workspace\Crunchy\dbname = C:\Users\username\Documents\Testing\database_test.sqlite3"
instead of
"C:\Users\username\Documents\Testing\database_test.sqlite3"

I think the possible fix might be the either change the regex in the split on line 96 to:
`            my ($key, $value) = split(/\s?=\s?/, $attrib, 2);`
or to change the regex on line 97 to:
`            if ( $key =~ /^(?:db(?:name)?|database)\s?$/ ) {`

This of course still leaves the question of why perl is looking under the eclipse workspace directory...one thing at a time, though.

**Comment by charsbar** [comment]
I'm not sure what you exactly did, but see https://metacpan.org/pod/DBI#connect first, and then try ```my $dbh = DBI->connect('dbi:SQLite:dbname=C:\Users\username\Documents\Testing\database_test.sqlite3') ```, note that single quotes to avoid escaping.

If your Eclipse does something weird, it's your (or possibly Eclipse's configuration) issue, not ours.

**Comment by troogyt** [comment]
Thanks for your feedback @charsbar.

I just noticed that in your example above you do not have spaces surrounding the '=', and checking my code it seems I do.
I checked the web page example I used and it appears they also have the spaces:
`my $dsn = "DBI:$driver:dbname = $database";`

**Comment by troogyt** [comment]
Thanks for your feedback @charsbar.

I just noticed that in your example above you do not have spaces surrounding the '=', and checking my code it seems I do.
I checked the web page example I used and it appears they also have the spaces:
`my $dsn = "DBI:$driver:dbname = $database";`
