### ISSUE TITLE
DBD::SQLite $sth->{TYPE} carries wrong kinds of values

### ISSUE THREAD

**Issue by hoehrmann** [DBD-SQLite/DBD-SQLite#36]
I believe the `TYPE` field in statement handles should have values suitable for use as 3rd parameter to `bind_parameter`, but currently you get strings indicating declared types (in contrast, `DBD::Pg` provides integer codes in the field).

The code commented out in https://github.com/DBD-SQLite/DBD-SQLite/blob/198ae95635aa38fdd0f5d74aa50f81012643f419/dbdimp.c#L1356 is probably correct.

To get a textual representation of the type, `DBI` users are supposed to use

```perl
use DBI;
use Test::More tests => 2;
my $dbh = DBI->connect('dbi:SQLite:dbname=:memory:');
my $sth = $dbh->prepare('SELECT CAST(1 AS INT) AS value');
$sth->execute();
my $type = $sth->{TYPE}[0];
unlike $type, qr/varchar/i, 'statement handle type info';
my $type_info = $dbh->type_info( $type );
like $type_info->{TYPE_NAME}, qr/INT/i, 'correct type_info for int literals';
```

But `DBD::SQLite` does not currently implement `type_info` at all, it seems.

`DBD::Pg` passes both tests above.

**Comment by charsbar** [comment]
It's been a known issue for years: https://rt.cpan.org/Ticket/Display.html?id=46873
Actually it's been violating DBI spec from the very start when it used sqlite2: https://metacpan.org/source/MSERGEANT/DBD-SQLite2-0.32/dbdimp.c#L662

Theoretically it's possible to change this behavior, but considering the current status of Perl and the environement it's in, I'd rather keep this as is, not to break backward compatibility. Sorry if this causes inconvenience for you.
