### ISSUE TITLE
DBD-SQLite-1.62 Install fails on v5.18.2 built for darwin-thread-multi-2level

### ISSUE THREAD

**Issue by bwva** [DBD-SQLite/DBD-SQLite#43]
Failure point:
make: *** No rule to make target `/System/Library/Perl/Extras/5.18/darwin-thread-multi-2level/auto/DBI/Driver_xst.h', needed by `SQLite.xsi'.  Stop.

Trying with --force doesn't help.

Full install log:
cpanm (App::cpanminus) 1.7044 on perl 5.018002 built for darwin-thread-multi-2level
Work directory is /Users/bw/.cpanm/work/1546365916.620
You have make /usr/bin/make
You have LWP 6.05
You have /usr/bin/tar: bsdtar 2.8.3 - libarchive 2.8.3
You have /usr/bin/unzip
Searching DBD::SQLite () on cpanmetadb ...
--> Working on DBD::SQLite
Fetching http://www.cpan.org/authors/id/I/IS/ISHIGAKI/DBD-SQLite-1.62.tar.gz
-> OK
Unpacking DBD-SQLite-1.62.tar.gz
Entering DBD-SQLite-1.62
Checking configure dependencies from META.json
Checking if you have DBI 1.57 ... Yes (1.631)
Checking if you have File::Spec 0.82 ... Yes (3.40)
Checking if you have ExtUtils::MakeMaker 6.58 ... Yes (6.66)
Configuring DBD-SQLite-1.62
Running Makefile.PL
Checking if your kit is complete...
Looks good
Using DBI 1.631 (for perl 5.018002 on darwin-thread-multi-2level) installed in /System/Library/Perl/Extras/5.18/darwin-thread-multi-2level/auto/DBI/
Writing Makefile for DBD::SQLite
Writing MYMETA.yml and MYMETA.json
-> OK
Checking dependencies from MYMETA.json ...
Checking if you have Test::Builder 0.86 ... Yes (1.302141)
Checking if you have Test::More 0.47 ... Yes (1.302141)
Checking if you have DBI 1.57 ... Yes (1.631)
Checking if you have ExtUtils::MakeMaker 0 ... Yes (6.66)
Checking if you have Tie::Hash 0 ... Yes (1.04)
Checking if you have File::Spec 0.82 ... Yes (3.40)
Building and testing DBD-SQLite-1.62
cp lib/DBD/SQLite/VirtualTable.pm blib/lib/DBD/SQLite/VirtualTable.pm
cp lib/DBD/SQLite/Fulltext_search.pod blib/lib/DBD/SQLite/Fulltext_search.pod
cp lib/DBD/SQLite/Cookbook.pod blib/lib/DBD/SQLite/Cookbook.pod
cp lib/DBD/SQLite/Constants.pm blib/lib/DBD/SQLite/Constants.pm
cp lib/DBD/SQLite.pm blib/lib/DBD/SQLite.pm
cp lib/DBD/SQLite/GetInfo.pm blib/lib/DBD/SQLite/GetInfo.pm
cp lib/DBD/SQLite/VirtualTable/PerlData.pm blib/lib/DBD/SQLite/VirtualTable/PerlData.pm
cp lib/DBD/SQLite/VirtualTable/FileContent.pm blib/lib/DBD/SQLite/VirtualTable/FileContent.pm
make: *** No rule to make target `/System/Library/Perl/Extras/5.18/darwin-thread-multi-2level/auto/DBI/Driver_xst.h', needed by `SQLite.xsi'.  Stop.
-> FAIL Installing DBD::SQLite failed. See /Users/bw/.cpanm/work/1546365916.620/build.log for details. Retry with --force to force install it.

**Comment by charsbar** [comment]
According to a CPAN Testers' report (see http://www.cpantesters.org/cpan/report/ebf659cc-0d68-11e9-84ec-97b8ef35c8bc), it should pass all the tests if you set up your environment properly. So please make sure first to (re)install DBI module with the same perl and the same cpanm command as you've tried to install DBD::SQLite.

**Comment by bwva** [comment]
On 1/1/19 at 10:56 AM, notifications@github.com (Kenichi Ishigaki) wrote:

> According to a CPAN Testers' report (see
> http://www.cpantesters.org/cpan/report/ebf659cc-0d68-11e9-84ec-
> 97b8ef35c8bc), it should pass all the tests if you set up your
> environment properly. So please make sure first to (re)install DBI
> module with the same perl and the same cpanm command as you've tried
> to install DBD::SQLite.

Thank you - that fixed it:

Successfully installed DBI-1.642 (upgraded from 1.631)
...
Successfully installed DBD-SQLite-1.62 (upgraded from 1.40)

Many thanks for your contributions to Perl!!

-- 

  - Bruce

_bruce__van_allen__santa_cruz__ca_
