### ISSUE TITLE
$dbh->quote() is broken for SQL_BLOB type

### ISSUE THREAD

**Issue by pali** [DBD-SQLite/DBD-SQLite#51]
Quoting normal string literals is working fine:
```
$ perl -Iblib/lib -Iblib/arch -MDBI -E 'my $dbh = DBI->connect("dbi:SQLite:dbname=:memory:", "", "", { sqlite_unicode => 1 }); say $dbh->quote("a\"\x{27}bc");'
'a"''bc'
```
Literal is put into apostrophes, and every apostrophe in the middle of the literal is duplicated. Double quotes in the middle are as is. So you can put output from `$dbh->quote` into SQL statement without SQL injection problems.
```
$ perl -Iblib/lib -Iblib/arch -MDBI -E 'my $dbh = DBI->connect("dbi:SQLite:dbname=:memory:", "", "", { sqlite_unicode => 1 }); say $dbh->selectrow_array("SELECT " . $dbh->quote("a\"\x{27}bc"));'
a"'bc
```

But quoting binary blobs is broken. It does not work at all. See:
```
$ perl -Iblib/lib -Iblib/arch -MDBI -E 'my $dbh = DBI->connect("dbi:SQLite:dbname=:memory:", "", "", { sqlite_unicode => 1 }); say $dbh->quote("a\"\x{27}bc", SQL_BLOB);'
a"'bc
```
Nothing was quoted. So putting it into SQL statement would cause SQL errors or injections.

According to SQLite documentation https://www.sqlite.org/lang_expr.html:
> BLOB literals are string literals containing hexadecimal data and preceded by a single "x" or "X" character. Example: X'53514C697465'

So correct quoting of `SQL_BLOB` should be: first do conversion into hex format and then quote it from left by `X'` and from right by `'`.

E.g. following implementation:
```perl
sub quote {
  my ($self, $value, $data_type) = @_;
  return q(X') . unpack('H*', $value) . q(') if $data_type == DBI::SQL_BLOB;
  return $self->SUPER::quote($value, $data_type);
}
```

**Comment by charsbar** [comment]
Applied a modified version of your patch. Thanks!
