### ISSUE TITLE
How to return BLOB from custom function?

### ISSUE THREAD

**Issue by zdm** [DBD-SQLite/DBD-SQLite#53]
Hi.
Is it possible to return BLOB value from the custom function, add with the sqlite_create_function() call?
Currently it is always returns UTF-8 encoded values.

**Comment by charsbar** [comment]
Currently no.

It's probably possible to let users return an arrayref like [$blob, SQL_BLOB], or, an object blessed by DBD::SQLite::BLOB to help DBD::SQLite use the correct sqlite3_result_* function, though.

Do you really need this feature?

**Comment by zdm** [comment]
Yes, I need it. I am using custom functions for sha calculation, but they are dies now, because it is trying to convert bytes array to the utf8.

**Comment by charsbar** [comment]
Do you have a sample code to test?

**Comment by zdm** [comment]
You can test with any digest function.
For example:
```
use Digest::MD5 qw[md5];
dbh->sqlite_create_function( 'md5', 1, sub { return defined $_[0] ? md5 $_[0] : undef } );

$dbh->selectall(q[SELECT md5('aaa')]);
```

**Comment by charsbar** [comment]
If the above code is really what you want to achieve, then it might be better not to use a custom function.
```
use Digest::MD5 qw[md5];

$md5 = md5($_) for @ {$dbh->selectall(q[SELECT 'aaa']) // [] };
```

Do you have a more realistic example?

**Comment by zdm** [comment]
This is just example.
Actually I am using queries, that uses hash functions internally and insert results the into the columns.
```
UPDATE "user" SET "hash" = md5("email") WHERE "id" = 1;
SELECT "hash" FROM "user";
```

**Comment by zdm** [comment]
I need that "hash" be the BLOB.

**Comment by charsbar** [comment]
Hmm. The above is a little better than before, but it still doesn't tell why you actually need it.
```
$sth = $dbh->prepare('UPDATE  user SET hash = ? WHERE id = ?');
$sth->bind_param(1, md5($email), SQL_BLOB);
$sth->bind_param(2, 1);
$sth->execute;
```

And why not using md5_hex (or md5_base64 if you prefer)? It's much more DBI-friendly.

**Comment by zdm** [comment]
;-)
Yes, because I am using this is triggers.

**Comment by charsbar** [comment]
It doesn't matter if it's called from a trigger or not. Using a trigger to make a hash of a blob (image, etc) is fine. What I'd like to know is why the function needs to return the value as a blob, instead of a text (md5_hex, etc), and a sample code to show the need. You just want it to be? Or is there any good reason?

**Comment by zdm** [comment]
I need to store hundreds of thousands  sha3_512 hashes. This is used in web-crawling software. I am using sqlite because software should be portable and should just work, without deploying additional DB server.
Store hashes in blob will take twice less size. And it is handy for me to work with the binary data.

Next reason - I am using uuid() function to generate default values for random primary keys. I also want to store this keys as BLOB.

It will be better to initially store this data in BLOB in sqlite driver, than write duplicate perl code everywhere, where this data is used.

I just asking, is it possible to do this? If this is hard to implement - let's forget.

**Comment by charsbar** [comment]
OK. Then could you try the following branch and see if it works for you? You can return ```[$value, SQL_BLOB]``` in the function you create.
https://github.com/DBD-SQLite/DBD-SQLite/tree/allow_created_function_to_return_blob

Currently DBD::SQLite is in a code freeze period and I'm not going to merge this until I release the next stable next month.
http://blogs.perl.org/users/kenichi_ishigaki/2019/07/next-stable-dbdsqlite-will-be-released-in-the-mid-august.html

**Comment by zdm** [comment]
Yes, I will try.
I already read you post several day ago. ;-)

**Comment by charsbar** [comment]
TODO: write more tests as this changes a common function
TODO: see if dbdimp_virtual_table.inc should also need to change, or not
TODO: doc

**Comment by zdm** [comment]
I tested, it works perfectly, waiting for release.

**Comment by zdm** [comment]
Thank you very much.Thank you very much.

**Comment by zdm** [comment]
Maybe it is better to return not an array ref but just one or two values.
First value - is always function result.
Second value - result type (if present and defined).

**Comment by charsbar** [comment]
I don't think so because that would change the context of a return value (especially of plain ```return;```.
Custom functions should always return a scalar value.

**Comment by zdm** [comment]
Hi, do I have a chance, that this improvement will be released?
I am currently rely on it, but if you don;t plan to release it i will need to rewrite a lot in the future.
Better to know this earlier.

**Comment by charsbar** [comment]
Thanks for the heads-up. It's about high time to release a new version at least for developers. The upstream SQLite has just entered pre-release testing, so maybe it's better to wait for their release to make ours stable, but anyway, I'll look into the todoes this weekend.

**Comment by zdm** [comment]
Got it, thanks.
I will wait.

**Comment by charsbar** [comment]
Closing as DBD::SQLite 1.66 is shipped. Thanks for your patience.
