### ISSUE TITLE
Placeholders in the HAVING clause do not work

### ISSUE THREAD

**Issue by az5112** [DBD-SQLite/DBD-SQLite#59]
The script below executes the following query:

```sql
	SELECT val, COUNT(*)
	FROM bug
	GROUP BY val 
	HAVING COUNT(*) > ?
```
When the placeholder is used, the query returns (incorrectly) an empty result set. The problem disappears when the placeholder in the query string is substituted with the actual value (`$query =~ s/\?/2/`).

```perl
#!/usr/bin/env perl
use strict;
use warnings;
use DBI;

my $setup_tables = <<SQL;
	CREATE TABLE bug(
		id INTEGER PRIMARY KEY,
		val INTEGER
	);
SQL

my $setup_data =<<SQL;
	INSERT INTO bug (val) VALUES
		(1), (1), (2), (2), (2), (3), (4)
SQL

my $query = <<SQL;
	SELECT val, COUNT(*)
	FROM bug
	GROUP BY val 
	HAVING COUNT(*) > ?
SQL

unlink 'bug.sqlite';
my $dbh = DBI->connect( 'dbi:SQLite:dbname=bug.sqlite', '', '', {
	AutoCommit => 1,
	RaiseError => 1,
	PrintError => 1
});

$dbh->do( $setup_tables );
$dbh->do( $setup_data );

my $HAVING_LIMIT = 2;
my $COUNT1 = scalar @{$dbh->selectall_arrayref($query, {Slice => {}}, $HAVING_LIMIT) };
$query =~ s/\?/$HAVING_LIMIT/e;
my $COUNT2 = scalar @{$dbh->selectall_arrayref($query, {Slice => {}}) };

warn "DBD::SQLite version = $DBD::SQLite::VERSION\n";
die "ERROR: different row counts: $COUNT1 vs $COUNT2\n" unless $COUNT1 == $COUNT2;
```

**Comment by charsbar** [comment]
Thanks for the report. This is a well-known documented glitch of the current implementation. See https://github.com/DBD-SQLite/DBD-SQLite/blob/master/lib/DBD/SQLite.pm#L1239 , and maybe older "stalled" tickets at https://rt.cpan.org/Public/Dist/Display.html?Name=DBD-SQLite for details.

**Comment by az5112** [comment]
Indeed - it is well documented with easy work-arounds.  I did go to CPAN before reporting but only checked if there was a Known Issues section.  (Maybe it would be a good idea to add one.)

I appreciate the fast response on the weekend!
