### ISSUE TITLE
Strange issue when using MAX(...) (max value from list) in UPDATE

### ISSUE THREAD

**Issue by aldem** [DBD-SQLite/DBD-SQLite#61]
Hi,

I have encountered strange issue that using MAX(value, ?) does not actually computes maximum when using DBD::SQlite.

To explain what happens, I will use this schema:
```SQL
CREATE TABLE data (
  id VARCHAR(255),
  value1 INTEGER
)
```
Then, I insert row with id = 'master' and value1 = 1:
```SQL
INSERT INTO data VALUES ('master', 1)
```

And now I will try to update to max of provided with parameter and existing:
```perl
$rc   = $db->do("UPDATE data SET value1 = MAX(value1, ?) WHERE id = 'master'", {}, 111);
```
So far so good - now `SELECT`ing from this row returns expected 111. But... Another update fails miserably:
```perl
$rc   = $db->do("UPDATE data SET value1 = MAX(value1, ?) WHERE id = 'master'", {}, 22);
```
The statement indicates successful update (1 updated row), but the resulting value of value1 is now 22, while 22 is definitely less than 111 and value1 should not change at all! Perhaps I misunderstood how `MAX()` supposed to work but then I don't understand why it works first time...

Initially I thought that this is some bug in sqlite itself, but I could not reproduce when using native (C) API. Trying to `SELECT MAX(value1, ?)` always works as expected, only `UPDATE` does not.

I have used most recent DBD::SQLite installable from CPAN (1.64), though earlier (included in CentOS 7 and Ubuntu 18.04) versions produce same result.

Either I overlook something or this is indeed a strange bug.

The code I used for testing:
```perl
use DBI;

my $rc;
my DBI $db = DBI->connect("dbi:SQLite:dbname=test.sqlite", undef, undef, { AutoCommit => 1 });

$db->do("DROP TABLE IF EXISTS DATA");
$db->do("CREATE TABLE data (id VARCHAR(255), value1 INTEGER)");
$db->do("INSERT INTO data VALUES ('master', 1)");
my $rows = $db->selectrow_arrayref("SELECT value1 FROM data");
print "Current value of value1: ", $rows->[0], ", setting to 111\n";
$rc   = $db->do("UPDATE data SET value1 = MAX(value1, ?) WHERE id = 'master'", {}, 111);
print "Update returned $rc\n";
$rows = $db->selectrow_arrayref("SELECT value1 FROM data");
print "Updated value of value1: ", $rows->[0], "\n";
$rc   = $db->do("UPDATE data SET value1 = MAX(value1, ?) WHERE id = 'master'", {}, 22);
print "Update returned $rc\n";
$rows = $db->selectrow_arrayref("SELECT value1 FROM data");
print "Updated value of value1: ", $rows->[0], "\n";
```
Changing AutoCommit mode to 0 makes no difference.

Any ideas?

Thank you!

**Comment by charsbar** [comment]
Hi. I can't say for sure but most probably this is because https://metacpan.org/pod/DBD::SQLite#Functions-And-Bind-Parameters .

**Comment by aldem** [comment]
@charsbar Thanks a lot, you saved my mind and a lot of time :)

Indeed, the weird "? + 0" trick did the job - so problem was in assuming all bound parameters to be strings (and sqlite, obviously, does not have strict type checking so it didn't complain).

Thus this (technically) is not really a bug, but very confusing nevertheless.

**Comment by charsbar** [comment]
Sorry for your inconvinience. Closing as a known issue.
