### ISSUE TITLE
incorrect offsets when using perl tokenizer with sql_unicode => 1

### ISSUE THREAD

**Issue by damil** [DBD-SQLite/DBD-SQLite#75]
if sql_unicode is activated, the FTS functions offsets(..) and snippet(...) report incorrect results. Somewhere the translation from character offsets to byte offsets is failing -- I haven't figured out where.
I will try to expand t/43_fts3.t to make this problem apparent.

**Comment by charsbar** [comment]
@damil Thanks for your report. It might be because https://github.com/DBD-SQLite/DBD-SQLite/issues/66 (and incomplete change by https://github.com/DBD-SQLite/DBD-SQLite/pull/67 if you use the master branch). I'm adding a flag for auto-downgrade and more tests for that.

**Comment by damil** [comment]
Thanks for the answer. It may well be the case that this bug was always present, because the offsets() and snippet() functions were not tested in the initial fts3 implementation, and I never tried to use them myself until a few days ago

**Comment by damil** [comment]
solved in https://github.com/DBD-SQLite/DBD-SQLite/commit/6669dbc332a3a7544b6a696a351964d72e224343
