### ISSUE TITLE
DBD::SQLite::db prepare failed: no such function: sqrt 

### ISSUE THREAD

**Issue by hurricup** [DBD-SQLite/DBD-SQLite#82]
For some reason can't eat sqrt function in a query.
DBD::SQLite: 1.66
OS: Windows 10
Perl: Strawberry Perl 5.32.1) 64 for MSWin32-x64-multi-thread

Fails even on simple query like `select sqrt(4)`

**Comment by hurricup** [comment]
Same error when trying in WSL (ubuntu 18)

**Comment by charsbar** [comment]
That's because your DBD::SQLite is not new enough and does not support built-in math functions. Install the latest developer release (1.67_07), or wait for the next stable version which will be released in a month.
