### ISSUE TITLE
The sqlite_unicode flag needs a better documentation

### ISSUE THREAD

**Issue by HaraldJoerg** [DBD-SQLite/DBD-SQLite#83]
The documentation says:

> If the attribute `$dbh->{sqlite_unicode}` is set, strings coming from the database and passed to the collation function will be properly tagged with the utf8 flag;

However, perlunifaq says:

> Please, unless you're hacking the internals, or debugging weirdness, don't think about the UTF8 flag at all.

I haven't done exhaustive testing, but the behavior _is_ weird:
- If `sqlite_unicode` is set, then strings coming from the database are decoded to characters.  Strings going to the database may contain unicode characters and must not be encoded.  This is all fine.
- if `sqlite_unicode` is _not_ set, then strings coming from the database are bytes which need to be decoded if the database contains non-ASCII characters.  Strings going to the database are encoded by DBD::SQLite _if their UTF8 flag is set, but regardless of whether they contain characters above 255 or not._  So, in this case if you INSERT one character "\N{EURO SIGN}" and then SELECT it back, you get three: "\x{e2}\x{82}\x{ac}".  If you INSERT a "\x{e4}" which doesn't have the UTF8 flag (e.g. because it came from reading an "ä" in Perl's default encodng), and then SELECT it back, you get the (UTF-8 encoded) replacement character U+FFFD. Ouch.

I would prefer if the documentation would say that if the attribute `$dbh->{sqlite_unicode}` is set, then users must pass their string values unencoded to the driver, and they get back decoded characters.  If the attribute is not set, then users must encode their string values if they contain non-ASCII characters, and they get bytes from the database which they need to decode to get the characters back.

Unfortunately I don't know whether my observations are correct or whether there's more to it, so I don't dare to formulate a pull request...

**Comment by charsbar** [comment]
You might want to try the latest developer release with a better set of flags, which is planned to be the next stable in a week or so: https://metacpan.org/release/ISHIGAKI/DBD-SQLite-1.67_07/view/lib/DBD/SQLite.pm#sqlite_string_mode

And, oh, I've overlooked that part of the documentation. It should be updated somehow to use the new flags. Thanks for pointing this out.

**Comment by HaraldJoerg** [comment]
Ah, excellent!  This looks great!
While we're at encoding (I am too lazy to open an extra issue): The documentation has `=encoding utf-8` which is fine, but the file itself is encoded in ISO-Latin 1.  This makes "naïve" from your repository look like "na�ve" in perldoc and on MetaCPAN.

I've now tried it... but apparently I don't understand the flags.  It seems that the UTF-8 flag still takes precendence?  When I set `DBD_SQLITE_STRING_MODE_UNICODE_STRICT` I would expect DBD::SQLite to always encode the strings, regardless of the flag.  Yet, when I provide a string which is already encoded, DBD::SQLite takes it "as is".

I'll attach my test file (named ".txt" due to GitHub restrictions).  What am I missing?
[encoding.txt](https://github.com/DBD-SQLite/DBD-SQLite/files/6823769/encoding.txt)

**Comment by HaraldJoerg** [comment]
I found my mistake.  I tripped over an example from the documentation of version 1.67: `$dbh->{string_mode} = DBD_SQLITE_STRING_MODE_UNICODE_FALLBACK;` - the key should read sqlite_string_mode.  This has already been fixed in 1.70, so everything is fine.
