### ISSUE TITLE
Documentation error in `string_mode`.

### ISSUE THREAD

**Issue by eekboek** [DBD-SQLite/DBD-SQLite#86]
The example code for `DBD_SQLITE_STRING_MODE_UNICODE_FALLBACK` uses the handle property `string_mode`, but DBD::SQLite 1.68 does not seem to have the short alternative. It needs to be `sqlite_string_mode`.

Setting `string_mode` is silently ignored.

**Comment by charsbar** [comment]
Already fixed in 2021.
