### ISSUE TITLE
Warnings about sqlite_unicode deprecation in code that doesn't use sqlite_unicode

### ISSUE THREAD

**Issue by AdamWill** [DBD-SQLite/DBD-SQLite#87]
Apologies for the slightly vague report, but I'm having trouble pinning this down any more specifically.

I maintain the Fedora package for openQA (an automated testing framework), which uses perl-DBD-SQLite, including in its test suite. Since, I think, the recent deprecation of sqlite_unicode, the package build is failing due to a warning in a test that asserts there should be no warnings:

    #   Failed test 'no (unexpected) warnings (via done_testing)'
    #   at ./t/25-cache.t line 450.
    # Got the following unexpected warnings:
    #   1: "sqlite_unicode" attribute will be deprecated. Use "sqlite_string_mode" instead. at /usr/lib64/perl5/vendor_perl/DBI.pm line 734.
    #   2: "sqlite_unicode" attribute will be deprecated. Use "sqlite_string_mode" instead. at /usr/lib64/perl5/vendor_perl/DBI.pm line 734.
    #   3: "sqlite_unicode" attribute will be deprecated. Use "sqlite_string_mode" instead. at /usr/lib64/perl5/vendor_perl/DBI.pm line 734.
    #   4: "sqlite_unicode" attribute will be deprecated. Use "sqlite_string_mode" instead. at /usr/lib64/perl5/vendor_perl/DBI.pm line 734.
    #   5: "sqlite_unicode" attribute will be deprecated. Use "sqlite_string_mode" instead. at /usr/lib64/perl5/vendor_perl/DBI.pm line 734.
    #   6: "sqlite_unicode" attribute will be deprecated. Use "sqlite_string_mode" instead. at /usr/lib64/perl5/vendor_perl/DBI.pm line 734.
    #   7: "sqlite_unicode" attribute will be deprecated. Use "sqlite_string_mode" instead. at /usr/lib64/perl5/vendor_perl/DBI.pm line 734.
    #   8: "sqlite_unicode" attribute will be deprecated. Use "sqlite_string_mode" instead. at /usr/lib64/perl5/vendor_perl/DBI.pm line 734.
    #   9: "sqlite_unicode" attribute will be deprecated. Use "sqlite_string_mode" instead. at /usr/lib64/perl5/vendor_perl/DBI.pm line 734.
    #   10: "sqlite_unicode" attribute will be deprecated. Use "sqlite_string_mode" instead. at /usr/lib64/perl5/vendor_perl/DBI.pm line 734.
    #   11: "sqlite_unicode" attribute will be deprecated. Use "sqlite_string_mode" instead. at /usr/lib64/perl5/vendor_perl/DBI.pm line 734.
    #   12: "sqlite_unicode" attribute will be deprecated. Use "sqlite_string_mode" instead. at /usr/lib64/perl5/vendor_perl/DBI.pm line 734.
    #   13: "sqlite_unicode" attribute will be deprecated. Use "sqlite_string_mode" instead. at /usr/lib64/perl5/vendor_perl/DBI.pm line 734.
    #   14: "sqlite_unicode" attribute will be deprecated. Use "sqlite_string_mode" instead. at /usr/lib64/perl5/vendor_perl/DBI.pm line 734.
    #   15: "sqlite_unicode" attribute will be deprecated. Use "sqlite_string_mode" instead. at /usr/lib64/perl5/vendor_perl/DBI.pm line 734.
    #   16: "sqlite_unicode" attribute will be deprecated. Use "sqlite_string_mode" instead. at /usr/lib64/perl5/vendor_perl/DBI.pm line 734.
    #   17: "sqlite_unicode" attribute will be deprecated. Use "sqlite_string_mode" instead. at /usr/lib64/perl5/vendor_perl/DBI.pm line 734.

line 734 of `DBI.pm` is, well, [this](https://github.com/perl5-dbi/dbi/blob/master/DBI.pm#L734). It's deep in the weeds of a complicated `connect` sub that I don't claim to fully understand. I can't figure out precisely where all the inputs for the particular loop that's causing the warning come from.

However, AFAICS, neither DBI nor anything in openQA are intentionally doing anything about unicode. I grepped the entire openQA codebase for the string 'unicode' and none of the results seem remotely relevant. The three tests that produce this warning (only one of them asserts there should be no warnings so the other two don't fail) don't seem to be doing anything obvious to trigger it, and neither does the underlying openQA code that actually sets up the sqlite DB.

Unfortunately I can't tell from the output of openQA's test suite *exactly* what operations in the tests cause the warning messages to be displayed, but from the number of warnings I think it happens pretty much any time the test does some kind of lookup in the sqlite DB.

**Comment by charsbar** [comment]
Sorry for the inconvenience. The warning seems to be coming from Mojo::SQLite ( https://metacpan.org/dist/Mojo-SQLite/source/lib/Mojo/SQLite.pm#L31 ), but it's probably better for DBD::SQLite to remove the warning. Shipped 1.69_01.

**Comment by AdamWill** [comment]
Aha, thanks for spotting that. Sorry, I don't know why I didn't think to check Mojo::SQLite. I'll send a patch for it.

**Comment by perlpunk** [comment]
Thanks @AdamWill and @charsbar 
When do you plan to release the next version?

**Comment by charsbar** [comment]
Hopefully in a few days when I get enough testers' reports.

**Comment by charsbar** [comment]
Already done.
