### ISSUE TITLE
Allow unregistering functions (ie. be able to use REGEXP from pcre.so)

### ISSUE THREAD

**Issue by nicomen** [DBD-SQLite/DBD-SQLite#88]
Right now we get a pure perl REGEXP method for "free", but if we want to use pcre.so (sqlite3_pcre on Debian/Ubuntu) and load the extension there seems to be no way to avoid the pure perl version overriding it.

The create_function method seems to allow unregistering a function by: " To delete an existing SQL function or aggregate, pass NULL pointers for all three function callbacks.", so I think this should be feasible?

https://www.sqlite.org/c3ref/create_function.html

**Comment by hoehrmann** [comment]
Works for me (error messages differ for the same regex before and after loading the extension):

```bash
% perl -MDBI -e 'my $dbh = DBI->connect("dbi:SQLite:dbname=:memory:"); $dbh->selectrow_array(q(SELECT REGEXP("(?{ warn })",1))); $dbh->sqlite_enable_load_extension(1); $dbh->sqlite_load_extension("/usr/lib/sqlite3/pcre.so"); $dbh->selectrow_array(q(SELECT REGEXP("(?{ warn })",1)));' 
DBD::SQLite::db selectrow_array failed: Eval-group not allowed at runtime, use re 'eval' in regex m/(?{ warn })/ at /home/bjoern/perl5/perlbrew/perls/hpx360perl-5.32.1d/lib/site_perl/5.32.1/x86_64-linux/DBD/SQLite.pm line 192.
DBD::SQLite::db selectrow_array failed: (?{ warn }): unrecognized character after (? or (?- (offset 2) at -e line 1.
```
