### ISSUE TITLE
cpanm install DBD::SQLite Error : DBI 1.57 is required to configure this module; please install it or upgrade your CPAN/CPANPLUS shell.

### ISSUE THREAD

**Issue by chaimol** [DBD-SQLite/DBD-SQLite#91]
```
Entering DBD-SQLite-1.70
Checking configure dependencies from META.json
Checking if you have ExtUtils::MakeMaker 6.58 ... Yes (7.62)
Checking if you have File::Spec 0.82 ... Yes (3.80)
Checking if you have DBI 1.57 ... Yes (1.643)
Configuring DBD-SQLite-1.70
Running Makefile.PL
DBI 1.57 is required to configure this module; please install it or upgrade your CPAN/CPANPLUS shell.
-> N/A
-> FAIL Configure failed for DBD-SQLite-1.70.
```
I have install DBI 1.643, but DBD-SQLite require DBI 1.57. So does the DBD-SQLite have to required DBI 1.57 ?

**Comment by charsbar** [comment]
If you have installed DBI 1.643 properly, that should work.

Please see if
* you are using the correct perl (system perl, or the one installed by plenv, perlbrew, etc)
* you are using the correct cpanm (ie. the one that uses the correct perl)
* you have installed DBI properly (`perl -MDBI -E 'say DBI->VERSION' ` should print the correct DBI version)

If you have updated (or changed) your perl recently, DBI may need to be reinstalled.

**Comment by chaimol** [comment]
Yes , This is course of DBI Error. Error is I have install many version DBI, I have install one DBI from rpm and put the path in ~/.bashrc, I also install another DBI by cpanm. So I run the `perl -MDBI -E 'say DBI->VERSION'`  out put is a new line but is empty.
after i delete the DBI path from my `~/.bashrc`,  run the command again will output the right version info of DBI "1.643". And then I install the DBD-SQLite success.
