### ISSUE TITLE
sqlite 3.37 now causes capitalization test case failure

### ISSUE THREAD

**Issue by jonringer** [DBD-SQLite/DBD-SQLite#92]
One of the test cases now fails with a capitalization error:

```
t/51_table_column_metadata.t .......................... 1/?
#   Failed test 'data type is correct'
#   at t/51_table_column_metadata.t line 22.
#          got: 'INTEGER'
#     expected: 'integer'

#   Failed test 'data type is correct'
#   at t/51_table_column_metadata.t line 22.
#          got: 'INTEGER'
#     expected: 'integer'
# Looks like you failed 2 tests of 32.
```

**Comment by charsbar** [comment]
@jonringer Do you mean you are updating the bundled library for your distribution? It has already been fixed in the latest developer release. If you do need to do so, please cherry-pick https://github.com/DBD-SQLite/DBD-SQLite/commit/ba4f472e7372dbf453444c7764d1c342e7af12b8

**Comment by jonringer** [comment]
Yes, I just saw the related commits in master. Sorry for the noise.

Looks like another contributors already applied the fixes in [148574](https://github.com/NixOS/nixpkgs/pull/148574)

**Comment by shadowcat-mst** [comment]
@charsbar I'm coming late to the game here, but this has caused test failures in a bunch of downstream places (including a requirement to patch DBIC) - is this a libsqlite change that you can't detect from perl space?

My first reaction was "this is basically a compat breakage for a lot of code" ... but if it can't reasonably be avoided, it can't reasonably be avoided; so I'd like to understand before attempting to have an actual opinion here.

**Comment by charsbar** [comment]
@shadowcat-mst , sorry for being late to reply (and it's been a long time; I hope you are well). 

> including a requirement to patch DBIC

Is it still true? cf. https://metacpan.org/dist/DBIx-Class/changes#L5

> is this a libsqlite change that you can't detect from perl space?

I noticed the change from this issue (sorry), but I thought (at least at that time) that the change was from the upstream (hopefully for a good reason) and it was up to the downstream maintainers to follow the change, as DBI (and its [DBI::DBD::Metadata](https://metacpan.org/pod/DBI::DBD::Metadata) etc) did not define the case-sensitivity of the type. From the standpoint of DBD::SQLite, it was just a change that only few advanced users would care, and they probably had some measure to mitigate compatibility issues with other database modules.

However, if my assumption is wrong and most of the modules have maintainer's issues now and only DBD::SQLite can fix the situation, and a new fix to this issue would not break important modules, then I would consider adding a fix to DBD::SQLite. 

What do you think?
