### ISSUE TITLE
DBD-SQLite-1.71_03 test failing on perls built with -DDEBUGGING

### ISSUE THREAD

**Issue by andk** [DBD-SQLite/DBD-SQLite#95]
http://matrix.cpantesters.org/?dist=DBD-SQLite%201.71_03 has a lot of red, all from my smoker. These are as far as I can see, all from perls built with -DDEBUGGING.

**Comment by charsbar** [comment]
Thank you for a good hint! I was wondering what was the difference between the results from the GH Actions and ones from the testers.

**Comment by charsbar** [comment]
Shipped 1.71_04.

**Comment by charsbar** [comment]
Shipped 1.71_05.

**Comment by andk** [comment]
I just watched my smoker running the first 8 tests and they all passed. :+1:

**Comment by charsbar** [comment]
Thank you!
